/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.latam.test.infoPeople;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import com.latam.project.InfoPeopleController;
import com.latam.project.request.RequestPerson;
import com.latam.project.response.ResponsePerson;
import com.latam.project.service.ServiceInfoPeople;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class ControllerInfoPeopleTest {
    
    @InjectMocks
    InfoPeopleController infoPeopleController = new InfoPeopleController();
    
    @Mock
    ServiceInfoPeople servicePeople;
    
    @Mock    
    RequestPerson request;
    
    @Before
    public void before() {
    	MockitoAnnotations.initMocks(this);
    	
    }
    
    @Test
    public void testGetInfoPerson() {
    	when(servicePeople.processData(Mockito.any())).thenReturn(Mockito.any());
    	ResponseEntity<ResponsePerson> response = infoPeopleController.getInfoPerson(request);
        assertEquals("Expected <<200>> ", HttpStatus.OK,
                response.getStatusCode());
    }

}
